### ISSUE TITLE
PR builds should validate publish stage of pipeline

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#341] opened 2019-12-04 20:51 UTC
An [issue](https://github.com/microsoft/dotnet-framework-docker/pull/467) was encountered recently that occurred during the publish phase of the build.  It would have been caught if the PR build had tested this stage.  Obviously there needs to be some variation here compared to what the official builds do since the PR build should not actually be publishing anything.  But it should attempt to execute as much of the pipeline as possible.

**Comment by MichaelSimons** [comment] 2020-04-27 15:37
Closing as a duplicate of https://github.com/dotnet/docker-tools/issues/474.

**Closed by MichaelSimons** 2020-04-27 15:37 UTC
Labels: area:infrastructure, enhancement, triaged
