### ISSUE TITLE
Auth issue communicating with GitHub

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#300] opened 2019-09-11 17:37 UTC
The GenerateTagsReadme command is getting an authentication issue when trying to download a readme file from the private mcrdocs repo:

```
Microsoft.DotNet.ImageBuilder Information: 0 : Getting contents of 'teams/dotnet/core/README.runtime-deps.md' using 'https://api.github.com/repos/Microsoft/mcrdocs/contents/teams/dotnet/core/README.runtime-deps.md?ref=heads/master'
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in /image-builder/src/ImageBuilder.cs:line 66
```

This appears to only be occurring in the master branch of dotnet-docker repo which is using a newer tag of the ImageBuilder image than other repos.

**Comment by MichaelSimons** [comment] 2019-09-11 18:04
The root cause is the same as https://github.com/dotnet/docker-tools/issues/296.  Closing as duplicate.

**Closed** 2019-09-11 18:04 UTC
Labels: duplicate
